import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Inter, Nunito, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const botFontDmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-bot-dm-sans",
});

const botFontPlayfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-bot-playfair",
});

const botFontInter = Inter({
  subsets: ["latin"],
  variable: "--font-bot-inter",
});

const botFontNunito = Nunito({
  subsets: ["latin"],
  variable: "--font-bot-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${botFontDmSans.variable} ${botFontPlayfair.variable} ${botFontInter.variable} ${botFontNunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
